### ISSUE TITLE
Building fails on Windows

### ISSUE THREAD

**Issue by wimdes5** [tudelft3d/City3D#10]
nmake build always ends in an error at 97%
I'm using following versions:
- Windows 10 
- VS 2022
- Boost 1.71 (building with the latest 1.80 throws lots of errors)
- CGAL 5.4.3
- GMP 6.2.1
- OpenCV 4.6.0
- QT 5.15.2
- Gurobi 9.52
- MPFR 4.1.1

It seems some wrong or missing dependency - has anyone succeeded in building under windows?
[error.txt](https://github.com/tudelft3d/City3D/files/10125647/error.txt)

**Comment by LiangliangNan** [comment]
Is your GMP and MPFR built with VS 2022?
Please use these libraries shiped with CGAL.

**Comment by wimdes5** [comment]
I now read the CGAL instructions a bit more carefully, and put the "GMP and MPFR libraries, for Windows 64bits" in the CGAL auxilary folder and it's compiling without errors. Thank you!
