### ISSUE TITLE
running of the given data 002.ply on the GUI

### ISSUE THREAD

**Issue by collenW** [tudelft3d/City3D#11]
Thank you for your contribution! I wonder how long it takes for the given data 002.ply to generate the final scene model on the GUI. I tried to run 002.ply data. After sending a warning "3 faces lie on the same supporting plane" during the reconstruction of the 130th building, the output information has never been updated. The reconstruction of the 130th building has taken 8 hours. I don't know whether it is because the building structure is complex and takes a long time, or my operation process has failed?

**Comment by yidahuang** [comment]
Hi, thanks for your feedback.  On my desktop, city3d for 002.ply model only runs 5mins. My environment is **64G** ram, AMD Ryzen threadripper 2920x 12-core processor,   **ubuntu** system, **CLion** IDE, under **release** mode, using **Gurobi** solver. can you give me more details as I have provided?

**Comment by collenW** [comment]
> Hi, thanks for your feedback. On my desktop, city3d for 002.ply model only runs 5mins. My environment is **64G** ram, AMD Ryzen threadripper 2920x 12-core processor, **ubuntu** system, **CLion** IDE, under **release** mode, using **Gurobi** solver. can you give me more details as I have provided?

Glad to receive your reply. My environment is **32G** ram, Intel(R) Core(TM) i5-10500 CPU, **windows10** system, **Visual Studio 2017** IDE, under **debug** mode, using **Gurobi** solver. I'm very sorry. I will run in release mode.

**Comment by collenW** [comment]
When I run in release mode, it is much faster. The progress bar was rebuilt to 81% in the GUI, which took only 4 minutes. This is the time to build the 130th building, and then stop updating. I don't know what happened here.
