### ISSUE TITLE
The problem of reconstructing building

### ISSUE THREAD

**Issue by DeoBye** [tudelft3d/City3D#12]
Thanks a lot for the opensource project! Here I want to ask some questions I meet when I use the project to run with my data. I tried with one building and the result is extremely high which I thought It might be the plane extruded from the footprint. But I do not know which section went wrong resulting the plane haven't been cut from reconstruction.
![RU(@7GJL2(Q}_D(7{SW``~I](https://user-images.githubusercontent.com/117378651/207584398-25c471a7-58fc-47c2-b17a-99eb1f8ee1ca.png)

**Comment by yidahuang** [comment]
Thanks for your feedback. can you share the source data, like the input point cloud and footprint?

**Comment by DeoBye** [comment]
Sure！

从 Windows 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>发送

发件人: Jin ***@***.***>
发送时间: 2022年12月14日 12:38
收件人: ***@***.***>
抄送: Chen, ***@***.***>; ***@***.***>
主题: Re: [tudelft3d/City3D] The problem of reconstructing building (Issue #12)


Thanks for your feedback. can you share the source data, like the input point cloud and footprint?

―

**Comment by DeoBye** [comment]
________________________________

**Comment by DeoBye** [comment]
[000W7NQ.zip](https://github.com/tudelft3d/City3D/files/10251372/000W7NQ.zip)

**Comment by yidahuang** [comment]
Hi, I just  tried your data and updated the code,  the new reuslt is like this, it should works now.
<img width="703" alt="CleanShot 2022-12-17 at 10 36 58@2x" src="https://user-images.githubusercontent.com/18398235/208235695-acd9c87f-e9d8-4e66-b2d5-6dd3c963c272.png">

**Comment by lihanhan** [comment]
Hello, I'm sorry to disturb you. I reconstructed the first building in the data data, but there was a reconstruction error. The binary process failed in the lower left corner of the interface. What's the problem?
![image](https://user-images.githubusercontent.com/46349819/224062165-77c4c7ad-1fad-4022-a4e8-d9f2eaf08846.png)
