### ISSUE TITLE
GeoJSON footprint requirements

### ISSUE THREAD

**Issue by wimdes5** [tudelft3d/City3D#15]
When opening .geojson files there's always the message: Warning: I can handle only simple GeoJSON format!
And reconstruction keeps failing with: - Warning: encountered non-simple foot print polygons.
So it seems City3D skips on footprints deemed non-simple?

Shapes are quite simple, without touching or intersections. When inspecting in QGIS no errors are found. Even a file with only a simple rectangle will throw this warning. What could be the reason, or can a working example .geojson file be provided?

Some test files: https://github.com/tudelft3d/City3D/files/10297499/2huizen.zip

**Comment by wimdes5** [comment]
I carefully recreated the files, alignment looks perfect both in qgis and in City3D
No offset when I check with lasinfo, but still no reconstruction :-(
[2huizen2a.zip](https://github.com/tudelft3d/City3D/files/10377259/2huizen2a.zip)

**Comment by yidahuang** [comment]
I looked into your data, there are some issue with your geojson file, there are two repeated points in your footprint data( the starting and ending point of each polygon). So it cannot pass non-simple test.  After removing one point, the results is like this, i think it is good.
<img width="674" alt="CleanShot 2023-01-10 at 10 20 28@2x" src="https://user-images.githubusercontent.com/18398235/211511486-8a8e9873-7f0b-46b2-890f-1290f4f285de.png">

**Comment by hugoledoux** [comment]
the specs of geojson *require* the first and last point to be the same, this is not an error, see https://www.rfc-editor.org/rfc/rfc7946.html#section-3.1.6

**Comment by yidahuang** [comment]
@hugoledoux, thanks for the correction (:
@wimdes5, I have updated the code. It should work for your data now.

**Comment by wimdes5** [comment]
Indeed this works, thank you! 
1 remaining detail is the height scale, how could this be corrected?

**Comment by wimdes5** [comment]
After some more testing: most buildings reconstruct fine, but regularly reconstruction hangs on a building.
I tried recommendations as described in issues #4 to no avail, experimenting with the weights traingle neither.
In this example with some less regular shapes reconstruction hangs on the 2nd building: [14huizen.zip](https://github.com/tudelft3d/City3D/files/10387449/14huizen.zip)
Or this church: [kerk.zip](https://github.com/tudelft3d/City3D/files/10387452/kerk.zip) 
All are from the same aerial lidar set

**Comment by LiangliangNan** [comment]
@wimdes5 What does "reconstruction hangs on a building" mean?
I checked your data and found that the point clouds hang above the footprint polygons. This is possible and not an error because from the footprint data we don't know the exact altitude (i.e., Z value) of the building. In theory, the ground plane 
should be extracted from the point cloud, but that information is also ignored during the reconstruction.  So you can solve this "hanging building" issue using one of the following solutions:
 - provide the actual Z value of the building in the footprint data (and of course modify the code in the GeoJSON loader to use it);
 - extract the actual ground plane from the point cloud and use it to correct the Z coordinate of the footprint;
 - if none of the above works, the Z value of the ground plane can be approximated by the lowest Z coordinate. This may cause a large error because the lower part of a building can be completely missing. But this is the closest value we can obtain from such data.

**Comment by wimdes5** [comment]
Thanks for the advice! The hanging is unrelated to the height question; I meant reconstruction gets stuck on specific buildings (using SCIP solver)

**Comment by yidahuang** [comment]
I use Gurobi and run your data,  the result is like this,
![screenshot_4](https://user-images.githubusercontent.com/18398235/215546274-b3655802-13d5-41e5-9c8b-eb4adc846b43.png)
the overall result looks good. I think the main reason you getting stuck is the scip solver, as the scale it can tackle is smaller than gurobi.

**Comment by wimdes5** [comment]
I can test with Gurobi now, but processing still hangs on complex buildings like the church. Did you use any specific parameters?

**Comment by wimdes5** [comment]
By increasing the 'numbers' parameter I could get the church to reconstruct.

Another (fairly complex) church I've been trying to reconstruct: [kerk2.zip](https://github.com/tudelft3d/City3D/files/10717432/kerk2.zip)
While experimenting with parameters sometimes one part improves, but another part deteriorates.
(The existing footprint on the front of the church is clipping too much, that's not the issue)

Some more information on the working and interaction of the various parameters would be great!


![image](https://user-images.githubusercontent.com/119525189/218338920-967345e4-25c5-4866-96ce-653a70af62d1.png)

**Comment by LiangliangNan** [comment]
@wimdes5 Thanks for the feedback.

> While experimenting with parameters sometimes one part improves, but another part deteriorates.

This is indeed one limitation of the method. I don't think it can be solved by simply tuning the parameters (It may work for this particular model, but cannot guaranttee for any other examples). 
One possible extension would be to decompose a model into a few regions according to is complexity (don't have a solution now and it needs further research) and reconstruct each region with a proper set of parameters. 
This is out of the scope of this (already published) paper, but are are always open to discussions.

**Comment by wimdes5** [comment]
OK that's clear. Is any more information on the parameters availabe?
And a last question, is the polygon regularisation implemented in the demo executables?

**Comment by LiangliangNan** [comment]
You can find more details about the effect of the parameters in the following papers:
 - PolyFit: https://3d.bk.tudelft.nl/liangliang/publications/2017/polyfit/polyfit.html
 - City3D: https://3d.bk.tudelft.nl/liangliang/publications/2022/city3d/city3d.pdf

Regarding polygon regularization,no executable is available in the current implementation, but I think it is quite easy to call this function from the source code (in [regularize_polygon.h](https://github.com/tudelft3d/City3D/blob/main/code/method/regularize_polygon.h))
