### ISSUE TITLE
Reconstruction result problem

### ISSUE THREAD

**Issue by lihanhan** [tudelft3d/City3D#17]
Hello, I'm sorry to disturb you. I reconstructed the first building in the data data, but there was a reconstruction error. The binary process failed in the lower left corner of the interface. What's the problem?
![1678373771240](https://user-images.githubusercontent.com/46349819/224062886-7e40746a-2578-4bd2-843a-2b54afe46044.jpg)

**Comment by yidahuang** [comment]
it looks like the solving failed,  which solver you used?  can you provide more details, like the platform, compiler, solver, etc

**Comment by lihanhan** [comment]
I'm sorry to trouble you. The platform uses WindowsX64 and the compiler is VS2017. 
solver:
Gurobi 9.5.2; 
QT 5.14.2;
CGAL 5.5.2;
boost 1_71_0;
OpenCV 3.46;
I replaced gurobi_c++mdd2019.lib with gurobi_c++mdd2017.lib when compiling. as shown below, I don't know if there is an error.
![image](https://user-images.githubusercontent.com/46349819/224183223-f34265c0-db9b-4e62-aad5-2e81e82c7489.png)
And when I debug the CLI_Example_1 project, I found an error, as follows.
![image](https://user-images.githubusercontent.com/46349819/224184158-729d7991-80e1-4288-84cb-367c7514ce3d.png)
Looking forward to your help！

**Comment by yidahuang** [comment]
Since you are using gurobi, do you also install the license? If not, it doesn't work.

**Comment by lihanhan** [comment]
![image](https://user-images.githubusercontent.com/46349819/224191896-ea2c537c-a09f-4755-b73e-67e46a94d348.png)
Thank you very much for your help. Your code is very good, and you also wrote about problems during the optimization process. I wish you a happy life and smooth work.
