### ISSUE TITLE
The problem with the results in Vaihingen data

### ISSUE THREAD

**Issue by lihanhan** [tudelft3d/City3D#19]
Hello, I am sorry to disturb you. I conducted the experiment without adding the footprint on the vaihingen data. However, the results are very different from the results of the paper. Is there a parameter or a specific step that needs to be changed?Because even if I change the alpha parameter in the alphashape process, I still can't get a better result. I would like to get your help !

![image](https://user-images.githubusercontent.com/46349819/227937893-7d1d4aae-c83b-4c54-8a32-56f7a96bb99b.png)

**Comment by yidahuang** [comment]
In my paper, we use a training set of  Vaihingen dataset that contains footprint, why do you need to generate footprint?

**Comment by lihanhan** [comment]
Ok, thanks for your reply. I would like to study the algorithm for generating footprint to get a good architectural model. Is the building footprint file in DXF format in the training set containing the building footprint that you mentioned?

**Comment by lihanhan** [comment]
Ok, thanks for your reply. I would like to study the algorithm for generating footprint to get a good architectural model. Is the building footprint file in DXF format in the training set containing the building footprint that you mentioned?

**Comment by yidahuang** [comment]
From my point of view, footprint generation may follow this pipeline:  3D point projection-->boundary extraction(using alpha shape or other)--> regularization and simplification (involving the detection of main direction, potential orthogonalization, parallelism, etc.). Hope it helps (:
Yes, the .dxf file is what you want, you can directly visualize it using qgis or other software.

**Comment by lihanhan** [comment]
Thanks for your reply and good luck with your work!
