### ISSUE TITLE
Support SCIP in "method/regularize_polygon.cpp"

### ISSUE THREAD

**Issue by LiangliangNan** [tudelft3d/City3D#2]
Now users have the option to use SCIP for face selection, but RegularizePolygon only supports Gurobi.

**Comment by wdcsimon** [comment]
Yes please, we do not have access to Gurobi at Whanganui District Council

**Comment by esgn** [comment]
Hi,
I'm working at the project accelerator of @ignf (french national mapping and cartographic agency). We recently did some preliminary tests using Polyfit (via CGAL) with IGNF photogrammetric digital surface model (https://github.com/ignfab/building-roof-pipeline) and would now be interested in testing this project with the LIDAR data we are in the process of acquiring. Gurobi being quite costly out of academic research, we are very interested in the full support of SCIP in City3D.
Would you have any idea when this support might be effective ?
Thanks for all your collective work

**Comment by LiangliangNan** [comment]
Hi all,
Thanks for your patience. Now the support of the open-source solver SCIP is fully functional (but with limited tests), but please note that the SCIP is a few times slower than the GUROBI solver.

Do let us know if any issues encountered when you use/test City3D.
