### ISSUE TITLE
the result problem

### ISSUE THREAD

**Issue by xinzheng798** [tudelft3d/City3D#24]
the point cloud and footprint
![Snipaste_2023-07-05_20-53-27](https://github.com/tudelft3d/City3D/assets/125725219/f6c0082d-0d27-4b33-9066-4d0ef7a744a1)
the result of building
![1](https://github.com/tudelft3d/City3D/assets/125725219/3b91fb5a-564b-4ce5-a8ac-7b2ae5100992)
this is my data
[building_48.zip](https://github.com/tudelft3d/City3D/files/11958061/building_48.zip)

**Comment by LiangliangNan** [comment]
@yidahuang It seems the optimization failed.

**Comment by yidahuang** [comment]
@xinzheng798, can you provide more information about the result, like the parameters, solver, compiler, etc. I strongly recommend using the template we provided to report the potential issues.

**Comment by xinzheng798** [comment]
maybe i know the problem thanks
