### ISSUE TITLE
Mesh model front and back problems

### ISSUE THREAD

**Issue by xinzheng798** [tudelft3d/City3D#25]
![2023-07-20 16-25-02屏幕截图](https://github.com/tudelft3d/City3D/assets/125725219/25fede4b-fed1-4532-9a8f-0609d2975b20)
When look at the created 3D model in Mapple and find that there are some models that are positive and some are negative.Please how to solve this problem?

**Comment by yidahuang** [comment]
![254822765-25fede4b-fed1-4532-9a8f-0609d2975b20](https://github.com/tudelft3d/City3D/assets/18398235/c6142d69-7aae-4ff0-8183-6cb49fa07650)
deselect this
