### ISSUE TITLE
Is it possible to use this software with linux on an Arm64 architecture?

### ISSUE THREAD

**Issue by jean306** [tudelft3d/City3D#26]
I would like to be able to use this software on a Lonovo yoga 11 inch tablet with a linux system (Ubuntu 22) mounted on android system. What is the procedure to follow to compile it and make it able to work? Thank you in advance, for any advice allowing me to move forward. Cordially. Mr Barret.

**Comment by LiangliangNan** [comment]
Please follow the instructions detailed in the ReadMe:
https://github.com/tudelft3d/City3D/blob/main/README.md#obtaining-city3d
