### ISSUE TITLE
Incompatible with latest version of CGAL (5.6)

### ISSUE THREAD

**Issue by axelpey** [tudelft3d/City3D#27]
As referred in https://github.com/CGAL/cgal/releases/tag/v5.6, the assertions used in the code, such as CGAL_triangulation_assertion, are no longer available. Build then breaks saying:

```bash
City3D/code/method/alpha_shape.h:168:3: error: use of undeclared identifier 'CGAL_triangulation_postcondition'
                CGAL_triangulation_postcondition(pFace != NULL);
```

I suppose a solution would be to indicate using CGAL 5.4 or 5.5, but not 5.6 (trying to install 5.4 myself right now to paliate to that).
Or update the code to use general assertions to be compatible with 5.6

**Comment by hugoledoux** [comment]
btw, installing and having multiple versions of CGAL is really easy if you follow this:
https://github.com/CGAL/cgal/wiki/Branch-Build#using-multiple-versions-of-cgal

**Comment by axelpey** [comment]
Yeah that's what I ended up doing - or relatively close, as described in 3.2 here: https://doc.cgal.org/latest/Manual/usage.html

**Comment by axelpey** [comment]
I think the last commit fixes this!
