### ISSUE TITLE
Dataset of 20K buildings

### ISSUE THREAD

**Issue by nhonth** [tudelft3d/City3D#3]
Thanks a lot for releasing the code. I have a question about the reconstruction results. Section 4.2 of the paper says that the reconstruction results are released as a new dataset consisting of 20K buildings. Has the new dataset been release? If not, do you have a timeline on when it will be released?

Best regards,

-- Nhon

**Comment by LiangliangNan** [comment]
@nhonth The dataset has been released https://github.com/yidahuang/City3D_dataset

**Comment by nhonth** [comment]
That is great. Thank you so much!
