### ISSUE TITLE
acquiring individual building footprints

### ISSUE THREAD

**Issue by collenW** [tudelft3d/City3D#31]
Thank you for your significant contributions to building reconstruction research. I understand from your paper that your work has resulted in a dataset, specifically mentioned are the '002.ply' file and the '002_footprint.obj' file in the provided data folder. I'm interested in accessing the original point cloud and the corresponding footprint for each individual building in this dataset. Could you please guide me on how to obtain these specific data files? I sincerely appreciate your assistance.

**Comment by LiangliangNan** [comment]
The is a link in the [Data](https://github.com/tudelft3d/City3D?tab=readme-ov-file#data) section of the readme file.
And here is the link that directly brings you to the dataset: https://github.com/yidahuang/City3D_dataset

Our dataset consists of cloud-model pairs (of files) for all the buildings that have been tested/reconstructed during the development of the City3D project. 
The original point clouds were obtained from three different datasets (i.e., [AHN3](https://github.com/yidahuang/City3D_dataset/tree/main/AHN3), [Dales3d](https://github.com/yidahuang/City3D_dataset/tree/main/Dales3d), and [Vaihingen](https://github.com/yidahuang/City3D_dataset/tree/main/Vaihingen)), and footprint data is not available for all of them. Thus, we only made available the input point cloud and the corresponding reconstructed 3D model for each building.

**Comment by collenW** [comment]
Thank you for your comprehensive answer! Based on the information in the paper, I understand that the AHN3 dataset includes corresponding footprints. Could you please provide access to these footprints?

**Comment by yidahuang** [comment]
The [Register of Buildings and Addresses](https://www.kadaster.nl/zakelijk/registraties/basisregistraties/bag) (BAG) is the most detailed, openly available data set on buildings and addresses in the Netherlands.
