### ISSUE TITLE
Install dependencies and build city3d in windows with visual studio 2022

### ISSUE THREAD

**Issue by QiaosiLi** [tudelft3d/City3D#33]
Thanks for sharing the codes of city3d, but we met some problems to install and build city3d recently. In May 2023, we successfully installed dependencies with vcpkg and build city3d with visual studio 2022 in Windows 10 system. When we tried to install and build city3d with the same method recently in another window computer, it seems that vcpkg doesn't connect with VS2022 as before (but I am not sure). I have installed all dependencies but the program cannot be built. 

For example, there is an error when we try to build city3d in VS2022: "City3D\code\method\alpha_shape.h(218): error C3861: 'CGAL_triangulation_postcondition': identifier not found". 

I am wondering if you find similar problem recently to build city3d recently. Do you have any suggestion to solve the problem, alternatively would you suggest any other straightforward way to build in windows. Thanks

**Comment by yidahuang** [comment]
Your problem looks like issue #27, but I have already fixed it, see commit"replace CGAL_triangulation_assertion" in the history. Do you try the new code?

**Comment by QiaosiLi** [comment]
Thanks for your reply. Yes, we cloned the latest code from github

**Comment by LiangliangNan** [comment]
As you can see from the announcement of the CGAL developers: https://github.com/CGAL/cgal/releases/tag/v5.6
starting from CGAL 5.6, the `CGAL_triangulation_assertion` has been removed, and you should use  `CGAL_assertion` instead.
