### ISSUE TITLE
[experiment] - Inquiry Regarding Polyfit Method Application on Airborne LiDAR Point Clouds

### ISSUE THREAD

**Issue by collenW** [tudelft3d/City3D#35]
"Thank you for your contribution! 
I recently read your paper 'City3D: Large-Scale Building Reconstruction from Airborne LiDAR Point Clouds', and was particularly intrigued by the experiments in Figure 1. 
![figure1](https://github.com/tudelft3d/City3D/assets/119860099/0bb07237-7460-417b-9b92-1a4f620a26c8)

In these experiments, I noticed that the input point clouds had minimal points on the bottom and facades. Remarkably, the Polyfit method seemed to effectively generate complete models despite these limitations.

However, I encountered a challenge when applying Polyfit to my dataset. As shown in Figure 2 of my aerial point clouds, the models generated failed to reconstruct the bottom portion as shown in the Figure 3. This issue seems to arise from the point clouds having non-closed bottoms with no points.
![figure2](https://github.com/tudelft3d/City3D/assets/119860099/bc4efe6e-709f-43fc-a315-13d04b372475)
![figure3](https://github.com/tudelft3d/City3D/assets/119860099/9ed6b15b-52d8-4fd3-b840-82662d3579d8)

I would greatly appreciate your guidance on using the Polyfit method for scenarios with limited bottom and facade points. Could you suggest strategies to enable effective model reconstruction from such point clouds?

**Comment by LiangliangNan** [comment]
* **limited bottom** or **no ground**
You could impose a ground plane on the extracted set of planes (for pairwise intersection) or insert ground points to the initial point cloud (for plane extraction) . 

* **limited or no facade points**
As we have demonstrated in our paper, two strategies could be useful.

  1) extract the boundaries (as polygons) from the roof points, and then extrude them to the ground to form vertical planes. These planes, together with the planes extracted from the roofs and ground, will allow a closed model.
  2) incoporate building footprint data, from which you can extrude vertical planes. These planes, together with the planes extracted from the roofs and ground, will allow a closed model.

**Comment by collenW** [comment]
Okay, I really appreciate your helpful advice. Thank you!
