### ISSUE TITLE
Cmake errors

### ISSUE THREAD

**Issue by jhzhang2077** [tudelft3d/City3D#38]
**Describe the bug**
I'm trying to build the code as you list in the guidance. But considering that there are too many dependencies which makes the configuration complex.

**Tell us how to reproduce the bug**
Could you please help me with the cmakelist file (in the root path)? Is it too simple to search the dependency libraries?
I'll appreciate it if you could offer me a sample to follow.

**Development/Running environment:**
 - OS: [e.g. Windows 11]
 - Compiler [e.g. MSVC 2022, Clang 11, GCC 10]
 - Debug or release?
Release

**Comment by LiangliangNan** [comment]
Sorry, I don't understand what issue you're facing.
Can you please elaborate on it? For example, give more details and be specific.

**Comment by jhzhang2077** [comment]
Sorry for not being clear. I just can't pass the build process follow the steps on Windows.
It always reports error for missing libraries and I wonder whether it is required to add more libraries in the cmakefile?
Thanks!

**Comment by LiangliangNan** [comment]
So far I haven't seen any useful information that I can rely on to get a clue what the issue is.

So what are the errors? This can be better explained by posting here the complete cmake log file.
