### ISSUE TITLE
footprint

### ISSUE THREAD

**Issue by najsdh** [tudelft3d/City3D#46]
Hello teacher, I have another question to ask. I'd like to know how your architectural footprint is generated. Since I now have the building footprint of an area, but store the vertex information of each building outline, I would like to know how to convert this information into a footprint file like the one provided in your project. If possible, could you please tell me what information V, Vn and Vt are in the footprint file?

**Comment by LiangliangNan** [comment]
In our implementation, we assume the footprint of a building is simply a polygon. Thus for a set of buildings, their footprint information is a set of polygonal faces whose Z coordinates are set to 0, and these faces are stored in an [OBJ file format](https://en.wikipedia.org/wiki/Wavefront_.obj_file).
