### ISSUE TITLE
[BUG] -After the Build process in ubuntu

### ISSUE THREAD

**Issue by Sanju-Sajimon** [tudelft3d/City3D#48]
Problem
After the build process i couldn't run CLI_Examples and showing like reading file failed unknown file format. Here i attached error messages which i saw .
![WhatsApp Image 2024-05-17 at 10 14 07 AM](https://github.com/tudelft3d/City3D/assets/170083920/0c549127-9d4d-4925-aafb-abf43cc09f96)

**Comment by LiangliangNan** [comment]
I see your file paths contain "/.../" (in Example_1) and also "//" (in Example_2), but I am not sure if Ubuntu can correctly parse such paths.
Can you modify your code to use the absolute paths of the input files to see if it makes any difference?
