### ISSUE TITLE
[BUG] - put here a short description of the issue

### ISSUE THREAD

**Issue by study313software** [tudelft3d/City3D#49]
**Describe the bug**
Bug:  cmd build error with CGAL 5.4.1
When I compile the project with x64 tools for VS2019:  there is a cmake error: CMake Error at code/method/CMakeLists.txt:51 (message):CGAL found, but v5.4 or above is required.  Please install CGAL v5.4 or above.
![2](https://github.com/tudelft3d/City3D/assets/41318959/8c9d2b93-0063-47a9-a864-60574e8a0a41)

I check the cmake.txt. In line 51, 
![3](https://github.com/tudelft3d/City3D/assets/41318959/339a836c-6d53-4f48-83da-3858735aa8cf)

However, I add the CGAL path to the enviroment. Like This:
![4](https://github.com/tudelft3d/City3D/assets/41318959/475838d4-5202-4143-8bab-15bf45088b06)

And the version of CGAL is 5.4.1 which is >=5.4
![5](https://github.com/tudelft3d/City3D/assets/41318959/a5fd823e-fc9a-4f69-98e1-bcc5a0baa0a3)

Is there anything wrong with my CGAL？ It seemed like the enviroment path don't work

**Development/Running environment:**
 - OS: Windows 10
 - Compiler  MSVC 2019

**Additional context**

**Comment by study313software** [comment]
Yes, I have the lower Version CGAL 4.7 in my computer. Is that effect the build of the project? And I don't put the CGAL 4.7 path in the enviroment.

**Comment by LiangliangNan** [comment]
Please change:
```
if (CGAL_FOUND)
    message(STATUS "Found CGAL: ${CGAL_VERSION}")
```
to
```
if (CGAL_FOUND)
    message(STATUS "Found CGAL v${CGAL_VERSION}: ${CGAL_INCLUDE_DIRS}")
```
This will print the include path of the found CGAL (making it easier to identify which version was actually found).

**Comment by study313software** [comment]
Thanks for your suggestion. I changed the message info. And the include path of the found CGAL is V5.4.1. 
![6](https://github.com/tudelft3d/City3D/assets/41318959/b74ed5d7-759b-4a03-a12a-9c615e28919a)

**Comment by study313software** [comment]
I changed line 47 in cmake. And now it can configure sucess(although missing lib Gurobi)
![10](https://github.com/tudelft3d/City3D/assets/41318959/6bcbec29-26e3-47f9-80bd-834ece503f8b)
![8](https://github.com/tudelft3d/City3D/assets/41318959/28b3d0c0-2bfd-4303-9775-f86e639b710d)
But I don't see any sln or project in release folder? Is there still anything wrong with my build process?
![9](https://github.com/tudelft3d/City3D/assets/41318959/06c03bfd-979b-43e9-afdf-c560163487b5)

**Comment by LiangliangNan** [comment]
For the empty ${CGAL_VERSION} variable, where did you get the CGAL code? Did you change anything after you download CGAL?


What commands did you use for the configuration process?
I guess you can continue to use "nmake" to build City3D. After that the exe file will be generated in the "bin" directory.
To generate project files for a specific IDE like Visual Studio. Please refer to CMake manuals.

Best,
--
Liangliang

**Comment by study313software** [comment]
Thanks for your suggestion!
When I download CGAL， I follow the tutorial in this link: [https://www.cnblogs.com/lmst-ytt/p/16690676.html](url)
I changed  the gmp folder of CGAL.
![11](https://github.com/tudelft3d/City3D/assets/41318959/d8878a52-d162-4c2e-8223-572284fc5cce)

With namke, I get exe in the bin folder. 
![12](https://github.com/tudelft3d/City3D/assets/41318959/b0b40559-3ce3-44f1-a9e3-b88059facf19)

What do you mean about CMake manuals?

**Comment by LiangliangNan** [comment]
I meant CMake documentation.

Glad you have successfully built City3D, so I am going to close this issue.

Best,
--
Liangliang
________________________________

**Comment by study313software** [comment]
Thanks for your reply again! I build the project in VS2019 and can debug the code now.Hope you have a great day！
