### ISSUE TITLE
Regularize poligon problems with gurobi_c++ on Windows

### ISSUE THREAD

**Issue by xpowert** [tudelft3d/City3D#5]
When I run the program I get error: 
`fatal error: gurobi_c++.h: No such file or directory
[build]     6 | #include <gurobi_c++.h> //use gurobi as the solver` 
I use the windows system, any suggestions on how to fix this? I use MinGW as a compiler.

**Comment by LiangliangNan** [comment]
Thanks for the question. 

I just realized that there was an error in the ReadMe file saying that the Gurobi solver is optional. Actually, the Gurobi solver is required for the polygon regularization step. This means you will have to install and build the program with Gurobi.

If you still encounter the problem after the installation of Gurobi, you can help CMake find Gurobi by specifying the paths of Gurobi in [FindGUROBI.cmake](./code/cmake/FindGUROBI.cmake). Besides, you also need to [obtain a license](https://www.gurobi.com/downloads/end-user-license-agreement-academic/) to use Gurobi, which is free for academic use.
