### ISSUE TITLE
Unexplained faces in constructed models

### ISSUE THREAD

**Issue by QiaosiLi** [tudelft3d/City3D#50]
Hello authors, we used the City3D tool to construct a building model with our airborne LiDAR point clouds and footprints generated from the LiDAR point cloud. Most of the results are good, but some model has unexplained parts as shown in the red boxes in the picture below. I have tried using footprint (CLI_Example_1) and without footprint (CLI_Example_2), and different parameters of number grow region, but some models still have this problem.  Could you suggest how to solve this problem? Thanks

![image](https://github.com/tudelft3d/City3D/assets/140426435/f3dcffd2-6c9c-4c4a-89b6-5fab9522ec1a)

**Comment by LiangliangNan** [comment]
For these models, you may need to tune the weights between the energy terms. Please refer to our paper for more details about these terms.

**Comment by yidahuang** [comment]
I recommend assigning a greater weight to the complexity term. Additionally, if you use our function to generate the footprint, please ensure that you specify a value for the z-coordinate, as the default value may be inappropriate for your specific cases.
