### ISSUE TITLE
cmake build settings without gui

### ISSUE THREAD

**Issue by baal-lgln** [tudelft3d/City3D#51]
Is there any way to build the project without the gui modules? I'm only interested in the cli part and would like to reduce the build time and resulting size.
OpenCV uses a build_list parameter for cmake like this: `cmake -DBUILD_LIST=core,highgui,improc ..`

**Comment by yidahuang** [comment]
You can just build the cli part without GUI by running CLI_Example_1 in the project, more info can be found in the readme file.
