### ISSUE TITLE
too much candidate faces

### ISSUE THREAD

**Issue by wfq007** [tudelft3d/City3D#54]
May I ask if there are a large number of candidate faces (50,000) generated during the reconstruction of some building point clouds, which causes the speed to be very slow. what is the reason for this, and where should I modify the parameters? Thank you!
![20240914170731](https://github.com/user-attachments/assets/48c00481-12ef-4023-a41b-521e2bd2c216)

**Comment by LiangliangNan** [comment]
Hi, sorry for the late response.
One main reason that causes too many candidate faces is the high complexity of a building (e.g., too many small plannar regions, too many hight jumps). This will lead to an MIP problem that cannot be solved within a reasonable time window.

Now this issue has been partially addressed by
- simplify the input footprint (leading to fewer vertical planes);
- in case of huge candiate faces, lines (inside the footprint polygon) are excluded from reconstruciton.

With these updates, you should be able to handle a lot more buildings. But still, too complex ones may still be too heavy for the algorithm. In such a case you may choose a smaller value for `max_allowed_candidate_faces`:
https://github.com/tudelft3d/City3D/blob/cfcc14b1f20d7d08d336a8ea52d904735d22b937/code/method/method_global.cpp#L19

**Comment by LiangliangNan** [comment]
We believe the issue has been resolved, so I am closing this issue now. Please feel free to reopen it if you encounter related problems.
