### ISSUE TITLE
[BUG] -No Generate Foot Print

### ISSUE THREAD

**Issue by ShuaibZyx** [tudelft3d/City3D#55]
**Describe the bug**
After importing the ply point cloud data and clicking on segmentation, no footprint was generated, resulting in an abnormally high reconstruction result. The roof does not match the point cloud data, please help me.

**Tell us how to reproduce the bug**
1. Load the data file `xxx.ply`. 
2. Click on 'segmentation',Click Generate Foot Print
3. Then it seems that no footprint was generated.

**Development/Running environment:**
 - OS: [e.g. Linux Ubuntu 20.04.1]
 - Compiler [e.g.  GCC 9.4.0]
 - release

Test data: [ply.zip](https://github.com/user-attachments/files/17529268/ply.zip)

**Additional context**
![image](https://github.com/user-attachments/assets/f2e3ca9c-1009-4a2f-8804-4ca05a833147)
![image](https://github.com/user-attachments/assets/3605968c-30a4-4b89-8009-7f3e1aca6048)

I think there might be an issue with the Foot Print generation.
Also, I was wondering how you determine the ground_height parameter from the data?
Thank you for your reply！！！

**Comment by yidahuang** [comment]
Hi, I have set the ground height to 0, and the resulting footprint appears as shown. 
![CleanShot 2024-10-26 at 16 55 59@2x](https://github.com/user-attachments/assets/b04bcbfd-dd6d-4899-803b-feb3e2ad8d10)
It seems that the input point clouds only capture the roof structures, making it inappropriate to use the lowest point height as a representation of the ground level.

If you have access to the complete raw point cloud data, including both the roof and ground points, it would be advisable to directly inspect the data and set the ground height based on the actual ground points.

However, if no ground-level data is available, an alternative approach is to experiment with different values. In your case, I used a ground height of 0, which may be a reasonable starting point for further adjustments.

**Comment by ShuaibZyx** [comment]
Thank you very much for your quick reply. Thank you very much! I re-implemented the program according to your suggestion, but surprisingly, foot print still did not appear. I recorded a video, could you please help me check what was wrong with it? Thanks again for your reply! @yidahuang 

https://github.com/user-attachments/assets/2824b1ed-f26e-426e-beea-5a8c61d4cd87

**Comment by yidahuang** [comment]
Thank you for your feedback. I’m not sure how you re-implemented the program, and I am unable to reproduce your results on my end. Could you kindly provide more details about all the changes you made? This will allow me to better understand the issue and assist you more effectively.

**Comment by LiangliangNan** [comment]
There was an improvement regarding plane detection in the last few days. So please test with the latest code and let us know if you still have the same problem.

**Comment by ShuaibZyx** [comment]
Hello, sorry for the late reply. I downloaded the latest code you provided and tried to run it again, many of the test files failed to generate the rebuilt model and produced multiple crashes, I really don't know how to fix it (maybe it's a parameter issue?). Can you please help me try it out, I need the results of this test set, thank you for your help.[我用夸克网盘分享了「Testset.zip」](https://pan.quark.cn/s/74f25ca63dbc)
