### ISSUE TITLE
[question] - How can I get footprint flile 

### ISSUE THREAD

**Issue by fisheatmice** [tudelft3d/City3D#56]
fiiles in city3D (https://github.com/yidahuang/City3D_dataset) have no footprint file, but in project's /data/ dir has ,how can We generate the footprint file

**Comment by yidahuang** [comment]
Hi, our dataset consists of cloud-model pairs (of files) for all the buildings that have been reconstructed during the development of the City3D project.
The original point clouds were obtained from three different datasets (i.e., [AHN3](https://github.com/yidahuang/City3D_dataset/tree/main/AHN3), [Dales3d](https://github.com/yidahuang/City3D_dataset/tree/main/Dales3d), and [Vaihingen](https://github.com/yidahuang/City3D_dataset/tree/main/Vaihingen)), and footprint data is only available for AHN3.
Thus, we only made available the input point cloud and the corresponding reconstructed 3D model for each building.


As we already stated in the readme, sources of footprint data may include:

The cadastre of the city/country. Many countries maintain footprint data through their cadastre, which may be publicly available or can be obtained by contacting the relevant authorities. For example, the footprint data for [AHN3](https://github.com/yidahuang/City3D_dataset/tree/main/AHN3) is available in [Register of Buildings and Addresses](https://www.kadaster.nl/zakelijk/registraties/basisregistraties/bag).

Open data platforms such as [OpenStreetMap](https://tudelft3d.github.io/3dfier/building_footprints_from_openstreetmap.html) may offer footprint data.

In case you have a point cloud of a scene containing multiple buildings, but don't have access to the footprint of the buildings, you will need to segment out the individual buildings either manually or using an automatic approach. There are various published papers addressing instance segmentation of urban buildings from point clouds. You can explore these methods to find one that fits your purpose, and then [CLI_Example_2](https://github.com/tudelft3d/City3D/tree/main/code/CLI_Example_2) will be suitable for the reconstruction.
