### ISSUE TITLE
Asking for your help.

### ISSUE THREAD

**Issue by ShuaibZyx** [tudelft3d/City3D#57]
Hello, sorry for the late reply(#55). I downloaded the latest code you provided and tried to run it again, many of the test files failed to generate the rebuilt model and produced multiple crashes, I really don't know how to fix it (maybe it's a parameter issue?). Can you please help me try it out, I need the results of this test set, thank you for your help.[我用夸克网盘分享了「Testset.zip」](https://pan.quark.cn/s/74f25ca63dbc) @LiangliangNan @yidahuang Thank You!!!

**Comment by LiangliangNan** [comment]
Can you post you data directly here?
(I don't have an account for the cloud storage you used for sharing the data).

**Comment by ShuaibZyx** [comment]
Sorry for that. GitHub only allows uploads of files no larger than 25M. Do you have any email address? I can try to send it to your email address. Or any other way that is convenient to you. Thanks!!

**Comment by LiangliangNan** [comment]
liangliang.nan AT tudelft.nl

**Comment by yidahuang** [comment]
Hi,

Thank you for sharing the data. After reviewing it, I wanted to check if you have scaled the coordinates of all the buildings to the range [-0.5, 0.5]. This scaling can significantly affect the parameters, especially during the plane detection stage. You can adjust the parameters accordingly in the code/method/point_set_region_growing.cpp. Line 43-45

	const FT search_sphere_radius = FT(8) / FT(100);
	const FT max_distance_to_plane = FT(4) / FT(100);
	const FT max_accepted_angle = FT(25);
	

I have a question regarding the data source. Our method is primarily designed for airborne LiDAR point clouds, which typically include a limited number of ground points around buildings—something our algorithm is able to handle. However, I observed that in some of your data samples, the number of ground points appears to exceed the number of roof points. This could potentially introduce ambiguity in the reconstruction process. Applying a preliminary ground filtering step might be beneficial to reduce these points and improve overall accuracy.

**Comment by ShuaibZyx** [comment]
Thank you for your reply, I did process the data in [-0. 5-0. 5], and then apply a simple code to project all the point clouds to the ground as a supplementary point. I thought this would be more beneficial to the model reconstruction. It seems that I made a mistake. I reprocessed the data, removed the ground point cloud, and then modified the code as you suggested, and this time footprint can generate, however, the reconstruction steps consistently report errors,。These are the error screenshots and processed data.
![d83ab0368e416285e001752292f067ae](https://github.com/user-attachments/assets/bf9c97c3-c718-42d7-9ec4-f615268008bb)
[Testset_NoGround.zip](https://github.com/user-attachments/files/18163310/Testset_NoGround.zip)
Looking forward to your reply. Thank you!!!

**Comment by yidahuang** [comment]
Hi,

I tested on the new dataset, and it works fine on my end:
![CleanShot 2024-12-17 at 17 59 08@2x](https://github.com/user-attachments/assets/9ac82b9b-4d47-4302-b226-3032798cd6a3)
Do you try the  latest version of the code?

**Comment by ShuaibZyx** [comment]
I've been trying for a long time, but I really can't use Qt to run the latest code. Is there any other way to run CLI_Example_2? I don't know much about C++. In addition, can you send me a copy of the results of successful operation, thank you so much. My email: 2631667689@qq.com or shuaibzyx@cug.edu.cn, or any other way that is convenient for you. Thank you again for your patient reply.

**Comment by LiangliangNan** [comment]
As Jin has explained, you should not scale the data (e.g., normalize the coordinates). The current code uses absolute distances as parameters, and these parameters are in units of real physical space distances.

**Comment by yidahuang** [comment]
I have sent you the reconstructed results, please check the email.

**Comment by yidahuang** [comment]
I am closing this issue, please open another one if u meet other issues.
