### ISSUE TITLE
faillure with a dataset

### ISSUE THREAD

**Issue by alavenant** [tudelft3d/City3D#8]
I unsuccessfully tested the tool with this dataset. 
The program (CLI_Example_2) takes a lot of time and finally crash.
Same with City3D : it's take time and a lot of memory, i must crash it manually.

Can you try and explain me where is the problem ? 

Thanks,
Antoine

[building_test.laz.zip](https://github.com/tudelft3d/City3D/files/9849991/building_test.laz.zip)

**Comment by yidahuang** [comment]
Hi, thanks for your feedback.
I checked your input data, and I found out that  it is actually a complete point cloud of the urban scene.
<img width="496" alt="CleanShot 2022-10-28 at 09 38 12@2x" src="https://user-images.githubusercontent.com/18398235/198531272-b08a7173-e9d6-4e52-a202-edbe99a21f45.png">
As we have explained in the readme( Run City3D--> Example_2), "The individual buildings have already been segmented and each building is stored as a separate point cloud file. Our method generates a footprint for each building and then reconstructs it. "  In this case, the input should be the point clouds of individual buildings, not the scan of the  whole  scene. Therefore,  I would suggest you firstly extract the individual building point clouds from the original input data.
